### ISSUE TITLE
DashMachine Info is outdated

### ISSUE THREAD

**Issue by basings** [tborychowski/self-hosted-cookbook#10]
it looks like this is outdated
https://github.com/tborychowski/self-hosted-cookbook/blob/master/apps/dashboard/dashmachine.md
https://github.com/rmountjoy92/DashMachine

**Comment by tborychowski** [comment]
Hi, thanks for reporting.
What exactly is outdated? (I checked the docker params and they look fine)

That said, unfortunately this is the side-effect of having a repo of that sort (or any "list" of apps that are in constant development).
It would be close to impossible for one person to keep everything updated, unless it's their day job :-)
