### ISSUE TITLE
contribute

### ISSUE THREAD

**Issue by ippocratis** [tborychowski/self-hosted-cookbook#11]
I love self-hosting on my Raspberry Pi
I've tried some software that not included in your repo
How can I contribute my docker-compose setups and guides to it?
I'm unfamiliar with GitHub pull requests but I could try that if you agree
For me it would be simpler if I just opened issues

**Comment by tborychowski** [comment]
Hi, 
Thanks for the offer!

If you want to make a PR, here's what you need to do:

0. Have your Github setup for local dev. (you have a pair of keys generated locally and your public key added to your github account ([gh docs](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent)).
1. Click "Fork" in the top-right corner:

![2023-01-17 at 14 05 05@2x](https://user-images.githubusercontent.com/392513/212920936-0fa95a2f-15f6-43b7-aae6-f991b5069df8.png)

This will make a copy of the cookbook repo in your Github space.

2. Then you add the apps/pages and edit what you want (you can do that through the github UI or clone the repo locally)
e.g. in terminal:
```sh
git clone https://github.com/tborychowski/self-hosted-cookbook.git # replaced with your repo git url
# make changes to files
git add --all .
git commit -m 'some new apps'
git push
```
3. Once you have "committed" the changes to your copy of the repo - you should see a "Create PR" button in the main repo page.
4. Click "Create PR" button and you have your PR.

--

But it's not a problem if you prefer the issues!
Just create an issue with the app (preferably in a similar structure: title, links, some description, screenshot if you can, `docker-compose.yml` content and any tips, tricks and other useful notes).
I will add them to the cookbook.

**Comment by ippocratis** [comment]
When I sync my fork to apply your changes and want to open a pull request the branch apper as 10 commints ahead.  the old commits reappear

Is there a way I can fix this from the UI?

for now i deleted my fork and re-forked

I hope I dont get too nooby 

thanks

**Comment by tborychowski** [comment]
"Sync with fork" should do that for you:
<img width="440" alt="2023-01-20 at 20 34 28@2x" src="https://user-images.githubusercontent.com/392513/213800603-c40d5296-d289-464d-98dc-45fef0a486cd.png">
