### ISSUE TITLE
Chevereto `No video support. Requires a paid license`

### ISSUE THREAD

**Issue by rodber** [tborychowski/self-hosted-cookbook#24]
Hello,

Thanks for your repository. My name is Rodolfo Berríos and I created Chevereto.

I'm happy to share that Chevereto supports video since v4.1.0: https://releases.chevereto.com/4.X/4.1/4.1.0.html (current v4.2.3)

Chevereto also has an Open Source edition: https://github.com/chevereto/chevereto

Here the pure docker commands/compose: https://hub.docker.com/r/chevereto/chevereto

Hope it helps!

**Comment by tborychowski** [comment]
Thanks! 
I will update it as soon as I can.
(unless you care to create a PR)

:-)
