### ISSUE TITLE
Problems with Shaarli

### ISSUE THREAD

**Issue by chrispratl** [tborychowski/self-hosted-cookbook#5]
Hey there,
I just wanted to try out Shaarli (bookmarking) with the latest master version - I just pulled shaarli/shaarli:master some minutes ago.

There is a problem when using your suggested volumes: Shaarli runs as user nginx (Uid 100, Gid 101), when mounting your volumes, Docker mounts them with root:root ownership (id 0 for user and group). As a result, the nginx process is unable to write both directories.
For the first setup (or I believe, for any request to the server), some module wants to write logs to the data directory and fails doing so. Hence, the request does not complete successfully.

In the official repo, Shaarli uses named volumes (and not directory mounting) which bypasses this problem.

By the way: Thanks for the repo! I really appreciate it!

**Comment by tborychowski** [comment]
Thanks for the tip.
I updated the readme: https://github.com/tborychowski/self-hosted-cookbook/blob/master/apps/bookmarks/shaarli.md#prerequisite

I really don't like named volumes, as they make it more difficult to track & control the size & backup of the container's data.
(at least in my small home lab setup 😄 )
