### ISSUE TITLE
❓ Homer Dashboard Icons

### ISSUE THREAD

**Issue by rantanlan** [tborychowski/self-hosted-cookbook#7]
Hey, love your cookbooks... more a question than an issue. Can you tell me where you got the icons for your homer dashboard in that screenshot? Pretty neat an minimalistic. Thanks.

**Comment by tborychowski** [comment]
Haha, thank you!
I actually made them myself, for a theme for my extension for Firefox:
- [PerfectHome](https://github.com/perfect-things/perfect-home) is the extension
- [Pure White](https://github.com/perfect-things/perfect-home-themes/tree/master/theme-pure-white) is the theme. You'll find the icons there.

**Comment by rantanlan** [comment]
thanks! 👍  guess I will be designing icons the next few days 😫
